/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerServerIdRouteImport } from './routes/server/$serverId'
import { Route as ServerServerIdIndexRouteImport } from './routes/server/$serverId.index'
import { Route as ServerServerIdMetricsRouteImport } from './routes/server/$serverId.metrics'
import { Route as ServerServerIdConsoleRouteImport } from './routes/server/$serverId.console'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerServerIdRoute = ServerServerIdRouteImport.update({
  id: '/server/$serverId',
  path: '/server/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerServerIdIndexRoute = ServerServerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServerServerIdRoute,
} as any)
const ServerServerIdMetricsRoute = ServerServerIdMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => ServerServerIdRoute,
} as any)
const ServerServerIdConsoleRoute = ServerServerIdConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => ServerServerIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users': typeof UsersRoute
  '/server/$serverId': typeof ServerServerIdRouteWithChildren
  '/server/$serverId/console': typeof ServerServerIdConsoleRoute
  '/server/$serverId/metrics': typeof ServerServerIdMetricsRoute
  '/server/$serverId/': typeof ServerServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users': typeof UsersRoute
  '/server/$serverId/console': typeof ServerServerIdConsoleRoute
  '/server/$serverId/metrics': typeof ServerServerIdMetricsRoute
  '/server/$serverId': typeof ServerServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/users': typeof UsersRoute
  '/server/$serverId': typeof ServerServerIdRouteWithChildren
  '/server/$serverId/console': typeof ServerServerIdConsoleRoute
  '/server/$serverId/metrics': typeof ServerServerIdMetricsRoute
  '/server/$serverId/': typeof ServerServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/users'
    | '/server/$serverId'
    | '/server/$serverId/console'
    | '/server/$serverId/metrics'
    | '/server/$serverId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/users'
    | '/server/$serverId/console'
    | '/server/$serverId/metrics'
    | '/server/$serverId'
  id:
    | '__root__'
    | '/'
    | '/users'
    | '/server/$serverId'
    | '/server/$serverId/console'
    | '/server/$serverId/metrics'
    | '/server/$serverId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersRoute: typeof UsersRoute
  ServerServerIdRoute: typeof ServerServerIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$serverId': {
      id: '/server/$serverId'
      path: '/server/$serverId'
      fullPath: '/server/$serverId'
      preLoaderRoute: typeof ServerServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$serverId/': {
      id: '/server/$serverId/'
      path: '/'
      fullPath: '/server/$serverId/'
      preLoaderRoute: typeof ServerServerIdIndexRouteImport
      parentRoute: typeof ServerServerIdRoute
    }
    '/server/$serverId/metrics': {
      id: '/server/$serverId/metrics'
      path: '/metrics'
      fullPath: '/server/$serverId/metrics'
      preLoaderRoute: typeof ServerServerIdMetricsRouteImport
      parentRoute: typeof ServerServerIdRoute
    }
    '/server/$serverId/console': {
      id: '/server/$serverId/console'
      path: '/console'
      fullPath: '/server/$serverId/console'
      preLoaderRoute: typeof ServerServerIdConsoleRouteImport
      parentRoute: typeof ServerServerIdRoute
    }
  }
}

interface ServerServerIdRouteChildren {
  ServerServerIdConsoleRoute: typeof ServerServerIdConsoleRoute
  ServerServerIdMetricsRoute: typeof ServerServerIdMetricsRoute
  ServerServerIdIndexRoute: typeof ServerServerIdIndexRoute
}

const ServerServerIdRouteChildren: ServerServerIdRouteChildren = {
  ServerServerIdConsoleRoute: ServerServerIdConsoleRoute,
  ServerServerIdMetricsRoute: ServerServerIdMetricsRoute,
  ServerServerIdIndexRoute: ServerServerIdIndexRoute,
}

const ServerServerIdRouteWithChildren = ServerServerIdRoute._addFileChildren(
  ServerServerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersRoute: UsersRoute,
  ServerServerIdRoute: ServerServerIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
